version: '3.9'

services:
  php:
    container_name: php_bridge
    build:
      context: ./docker/php
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/app

  nginx:
    container_name: nginx_bridge
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php