name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Executando composer install para dependências da API
      uses: php-actions/composer@v5
      with:
        php_version: 8.2
        version: 2
        dev: no
        args: -o --ignore-platform-reqs -d ./app


    - name: Copiando arquivos dos plugins para ambiente de testes
      uses: burnett01/rsync-deployments@5.1
      with:
         switches: --no-perms -O --exclude=.git/ --exclude=.env --exclude=node_modules --delete -Prltvz
         path: ./app
         remote_path: /home/ubuntu/chatwoot-typebot-bridge-master/app
         remote_host: ${{ secrets.SSH_DEV_DEPLOY_HOST }}
         remote_port: 22
         remote_user: ubuntu
         remote_key: ${{ secrets.SSH_DEV_DEPLOY_KEY }}
