name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Executando composer install para dependências da API
      uses: php-actions/composer@v5
      with:
        php_version: 8.2
        version: 2
        dev: no
        args: -o --ignore-platform-reqs -d ./app


