name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Executando composer install para dependências da API
      uses: php-actions/composer@v5
      with:
        php_version: 8.2
        version: 2
        dev: no
        args: -o --ignore-platform-reqs -d ./app


    - name: Copiando arquivos do puglin  para ambiente de testes
      uses: burnett01/rsync-deployments@5.1
      with:
         switches: --no-perms -O --exclude=.git/ --exclude=.env --merge= "rsync-filter.txt"--exclude=node_modules --delete -Prltvz
         path: ./app
         remote_path: /home/ubuntu/chatwoot-typebot-bridge-master/app
         remote_host: ${{ secrets.SSH_DEV_DEPLOY_HOST }}
         remote_port: 22
         remote_user: ubuntu
         remote_key: ${{ secrets.SSH_DEV_DEPLOY_KEY }}

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_DEV_DEPLOY_HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_DEV_DEPLOY_KEY }}
        port: 22
        script: cd  /home/ubuntu/chatwoot-typebot-bridge-master/ && docker-compose up -d --force-recreate --build
